### ISSUE TITLE
EXTERNAL_LISTEN_HOSTS not respected, containers bind to 0.0.0.0

### ISSUE THREAD

**Issue by yaourdt** [anyproto/any-sync-dockercompose#139]
### Have you read a contributing guide?

- [x] I have read CONTRIBUTING.md
- [x] I have searched the existing issues and didn't find any that were similar
- [x] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

According to your docs, if specifying a single or a number of IP addresses in `EXTERNAL_LISTEN_HOSTS` in `.env.override` containers will respect that and bind to the respective IP addresses only.

![Image](https://github.com/user-attachments/assets/50400ae4-6906-4cd7-95e6-3c2a11747efd)

This is, however, not the case, as the supplied `docker-compose.yml` is defective in several places. See eg. lines 100ff as currently implemented:

```
any-sync-coordinator:
...
    ports:
      - "${ANY_SYNC_COORDINATOR_PORT}:${ANY_SYNC_COORDINATOR_PORT}"
      - "${ANY_SYNC_COORDINATOR_QUIC_PORT}:${ANY_SYNC_COORDINATOR_QUIC_PORT}/udp"
```
instead of the correct version
```
any-sync-coordinator:
...
    ports:
      - "${EXTERNAL_LISTEN_HOSTS}:${ANY_SYNC_COORDINATOR_PORT}:${ANY_SYNC_COORDINATOR_PORT}"
      - "${EXTERNAL_LISTEN_HOSTS}:${ANY_SYNC_COORDINATOR_QUIC_PORT}:${ANY_SYNC_COORDINATOR_QUIC_PORT}/udp"
```

This results in all affected containers binding to `0.0.0.0` instead of the selected interfaces, making them fully available to the public without authentication:

![Image](https://github.com/user-attachments/assets/ae561381-d1db-4634-b434-c16abaafd304)

### Expected Behavior

Containers should respect `EXTERNAL_LISTEN_HOSTS` as stated in your documentation instead of silently binding all (public) interfaces.

### Steps To Reproduce

Clone this repository, run `make start`with default settings.

### Environment

```markdown
- OS: ubuntu 
- Version: 24.04
```

### Anything else?

I initially tried to report this to security@anytype.io, but have gotten no further communication apart from an automatic reply that you received the message.

**Comment by fb929** [comment]
this is expected behavior:
the addresses in `EXTERNAL_LISTEN_HOSTS` are added to the server's and clients' **network config** (see: [network config](https://github.com/anyproto/any-sync-dockercompose/wiki/Usage#get-current-network-config) and the file `$(pwd)/etc/client.yml`).

`EXTERNAL_LISTEN_HOSTS` can include not only IP addresses, but also DNS names.
moreover, the IP address doesn’t even have to exist on your Docker host - for example, if you’re using an external TCP proxy.

if you need to restrict listening, you can do it yourself:

* If you're using **docker-compose v1.x.x**, use an docker-compose.override.yml config like:
   ```
   ---
   services:
     any-sync-coordinator:
       ports:
         - "192.168.1.2:${ANY_SYNC_COORDINATOR_PORT}:${ANY_SYNC_COORDINATOR_PORT}"
         - "192.168.1.2:${ANY_SYNC_COORDINATOR_QUIC_PORT}:${ANY_SYNC_COORDINATOR_QUIC_PORT}/udp"
         - "${ANY_SYNC_COORDINATOR_METRIC_ADDR}:8000"
     any-sync-filenode:
       ports:
         - "192.168.1.2:${ANY_SYNC_FILENODE_PORT}:${ANY_SYNC_FILENODE_PORT}"
         - "192.168.1.2:${ANY_SYNC_FILENODE_QUIC_PORT}:${ANY_SYNC_FILENODE_QUIC_PORT}/udp"
         - "${ANY_SYNC_FILENODE_METRIC_ADDR}:8000"
     any-sync-node-1:
       ports:
         - "192.168.1.2:${ANY_SYNC_NODE_1_PORT}:${ANY_SYNC_NODE_1_PORT}"
         - "192.168.1.2:${ANY_SYNC_NODE_1_QUIC_PORT}:${ANY_SYNC_NODE_1_QUIC_PORT}/udp"
         - "${ANY_SYNC_NODE_1_API_SERVER_ADDR}:8080"
         - "${ANY_SYNC_NODE_1_METRIC_ADDR}:8000"
     any-sync-node-2:
       ports:
         - "192.168.1.2:${ANY_SYNC_NODE_2_PORT}:${ANY_SYNC_NODE_2_PORT}"
         - "192.168.1.2:${ANY_SYNC_NODE_2_QUIC_PORT}:${ANY_SYNC_NODE_2_QUIC_PORT}/udp"
         - "${ANY_SYNC_NODE_2_API_SERVER_ADDR}:8080"
         - "${ANY_SYNC_NODE_2_METRIC_ADDR}:8000"
     any-sync-node-3:
       ports:
         - "192.168.1.2:${ANY_SYNC_NODE_3_PORT}:${ANY_SYNC_NODE_3_PORT}"
         - "192.168.1.2:${ANY_SYNC_NODE_3_QUIC_PORT}:${ANY_SYNC_NODE_3_QUIC_PORT}/udp"
         - "${ANY_SYNC_NODE_3_API_SERVER_ADDR}:8080"
         - "${ANY_SYNC_NODE_3_METRIC_ADDR}:8000"
     any-sync-consensusnode:
       ports:
         - "192.168.1.2:${ANY_SYNC_CONSENSUSNODE_PORT}:${ANY_SYNC_CONSENSUSNODE_PORT}"
         - "192.168.1.2:${ANY_SYNC_CONSENSUSNODE_QUIC_PORT}:${ANY_SYNC_CONSENSUSNODE_QUIC_PORT}/udp"
         - "${ANY_SYNC_CONSENSUSNODE_METRIC_ADDR}:8000"
   ```

* If you're using **docker-compose v2.x.x**, you'll need to modify the main `docker-compose.yml` file directly, following the same pattern as the override above.
