### ISSUE TITLE
Client connection error, "space is missing" on the node

### ISSUE THREAD

**Issue by andscape-dev** [anyproto/any-sync-dockercompose#140]
### Have you read a contributing guide?

- [x] I have read CONTRIBUTING.md
- [x] I have searched the existing issues and didn't find any that were similar
- [x] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I'm attempting a first installation of the AnySync stack. I've made some changes to the setup to fit my existing infra, and removed nodes 2 and 3 to minimize resource consumption (editing the config files accordingly).

I've checked that all nodes are accessible to each other and to the client. Until I try to connect the client everything seems to be working fine, no significant errors in the logs that I can tell. Once I try to connect the client, though, I get a bunch of errors in the node-1 saying "space is missing". It happens both with the default space when creating a new identity and with newly created spaces. It seems like I can't create any space at all, the spaces count in the logs stays at 0 no matter what. From the client I just see the red "Error" icon in the network status.

Here's my docker-compose.yaml

```yaml
services:
  mongo:
    container_name: anysync-mongo
    image: mongo:latest
    labels:
      stack: anysync
    restart: unless-stopped
    networks:
      anysync:
        ipv4_address: 172.0.10.10
    command: ["--replSet", "rs0", "--port", "27001"]
    volumes:
      - ${DATA_DIR}/anysync/mongo:/data/db:Z
    healthcheck:
      test: test $$(mongosh --port 27001 --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"anysync-mongo:27001\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s

  redis:
    container_name: anysync-redis
    image: redis/redis-stack-server:latest
    labels:
      stack: anysync
    restart: unless-stopped
    networks:
      anysync:
        ipv4_address: 172.0.10.20
    command: ["redis-server", "--port", "6379", "--dir", "/data/", "--appendonly", "yes", "--maxmemory", "256mb", "--maxmemory-policy", "noeviction", "--protected-mode", "no", "--loadmodule", "/opt/redis-stack/lib/redisbloom.so"]
    volumes:
      - ${DATA_DIR}/anysync/redis:/data:Z
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "-p", "6379", "incr", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 3

  minio:
    container_name: anysync-minio
    image: minio/minio:latest
    labels:
      stack: anysync
    restart: unless-stopped
    networks:
      anysync:
        ipv4_address: 172.0.10.30
        aliases:
          - "anysync.minio" # <bucket-name>.<endpoint-name>
    command: ["server", "/data", "--console-address", ":9001", "--address", ":9000"]
    environment:
      MINIO_ROOT_USER: VU7DRJBVKM6EPIAODYUD
      MINIO_ROOT_PASSWORD: "@^laVARL2$nVcLz*q1naoi&*jjaVzOx*33d&gNhT"
    volumes:
      - ${DATA_DIR}/anysync/minio:/data:Z
    healthcheck:
      test: bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  anysync-coordinator:
    container_name: anysync-coordinator
    image: ghcr.io/anyproto/any-sync-coordinator:latest
    labels:
      stack: anysync
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      anysync:
        ipv4_address: 172.0.10.40
      proxy-anysync:
        ipv4_address: 172.0.20.20
    volumes:
      - ${CONFIG_DIR}/homeserver/stacks/anysync/etc/any-sync-coordinator:/etc/any-sync-coordinator:Z
      - ${DATA_DIR}/anysync/networkStore/any-sync-coordinator:/networkStore:Z
    deploy:
      resources:
        limits:
          memory: 500M

  anysync-filenode:
    container_name: anysync-filenode
    image: ghcr.io/anyproto/any-sync-filenode:latest
    labels:
      stack: anysync
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      anysync-coordinator:
        condition: service_started
    networks:
      anysync:
        ipv4_address: 172.0.10.50
      proxy-anysync:
        ipv4_address: 172.0.20.30
    volumes:
      - ${CONFIG_DIR}/homeserver/stacks/anysync/etc/any-sync-filenode:/etc/any-sync-filenode:Z
      - ${CONFIG_DIR}/homeserver/stacks/anysync/.aws:/root/.aws:ro
      - ${DATA_DIR}/anysync/networkStore/any-sync-filenode:/networkStore:Z
    deploy:
      resources:
        limits:
          memory: 500M

  anysync-node-1:
    container_name: anysync-node-1
    image: ghcr.io/anyproto/any-sync-node:latest
    labels:
      stack: anysync
    restart: unless-stopped
    depends_on:
      anysync-coordinator:
        condition: service_started
    networks:
      anysync:
        ipv4_address: 172.0.10.60
      proxy-anysync:
        ipv4_address: 172.0.20.40
    volumes:
      - ${CONFIG_DIR}/homeserver/stacks/anysync/etc/any-sync-node-1:/etc/any-sync-node:Z
      - ${DATA_DIR}/anysync/any-sync-node-1:/storage:Z
      - ${DATA_DIR}/anysync/anyStorage/any-sync-node-1:/anyStorage:Z
      - ${DATA_DIR}/anysync/networkStore/any-sync-node-1:/networkStore:Z
    deploy:
      resources:
        limits:
          memory: 500M

  anysync-consensusnode:
    container_name: anysync-consensusnode
    image: ghcr.io/anyproto/any-sync-consensusnode:latest
    labels:
      stack: anysync
    restart: unless-stopped
    depends_on:
      anysync-coordinator:
        condition: service_started
    networks:
      anysync:
        ipv4_address: 172.0.10.70
      proxy-anysync:
        ipv4_address: 172.0.20.50
    volumes:
      - ${CONFIG_DIR}/homeserver/stacks/anysync/etc/any-sync-consensusnode:/etc/any-sync-consensusnode:Z
      - ${DATA_DIR}/anysync/networkStore/any-sync-consensusnode:/networkStore:Z
    deploy:
      resources:
        limits:
          memory: 500M

  anysync-netcheck:
    container_name: anysync-netcheck
    image: ghcr.io/anyproto/any-sync-tools:latest
    labels:
      stack: anysync
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - anysync-consensusnode
      - anysync-filenode
      - anysync-coordinator
      - anysync-node-1
    networks:
      anysync:
        ipv4_address: 172.0.10.80
    volumes:
      - ${DATA_DIR}/anysync:/code/storage:Z
    command: ["tail", "-f", "/dev/null"]
    stop_signal: SIGKILL
    tty: true
    healthcheck:
      test: any-sync-netcheck -c /code/storage/docker-generateconfig/nodes.yml 2>&1| grep -E 'netcheck\s+success'
      interval: 10s
      start_period: 5s

networks:
  anysync:
    name: anysync
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.0.10.0/24
  proxy-anysync:
    name: proxy-anysync
    external: true
```

### Expected Behavior

Logging into a fresh account from the official (MacOS) client, or creating a new space manually from an existing account, the client should show a green marker in the network status.

### Steps To Reproduce

- Create a new instance of each container
- Start the client already logged into the vault
- The client shows the untouched default space, and a red "Error" icon in the network status
- Stop the containers

### Environment

```markdown
- OS: macOS 14
- Client Version: 0.46.4
- Node Version: v0.6.4
- File Node Version: v0.8.5
- Consensus Node Version: v0.2.2
- Coordinator Version: v0.4.4
```

### Anything else?

Logs attached, IDs removed

[anysync-consensusnode.log](https://github.com/user-attachments/files/20029821/anysync-consensusnode.log)
[anysync-coordinator.log](https://github.com/user-attachments/files/20029818/anysync-coordinator.log)
[anysync-filenode.log](https://github.com/user-attachments/files/20029819/anysync-filenode.log)
[anysync-node-1.log](https://github.com/user-attachments/files/20029820/anysync-node-1.log)
