### ISSUE TITLE
The client cannot sync after changing EXTERNAL_LISTEN_HOSTS 

### ISSUE THREAD

**Issue by ms-xie** [anyproto/any-sync-dockercompose#45]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [x] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

After changing the `EXTERNAL_LISTEN_HOSTS` in `.env.override` and restart the docker compose, the client (which is login before) cannot sync and stuck on “preparing”.
re-logout / login not help.

**My current workaround**: 
delete all folder in `data Directory` and re-sync all data.

### Expected Behavior

The client can sync after upload new `client.yml` and without fetch all data again.

### Steps To Reproduce

1. edit `EXTERNAL_LISTEN_HOSTS` in `.env.override`
2. restart the docker compose `make restart`
3. export the new `client.yml`
4. upload new `client.yml` in client
5. enter the key
6. the client (which is login before) cannot sync and stuck on “preparing”

### Environment

```markdown
- OS: Docker-in-Docker-DinD v26.0.0 under unRaid 6.9.2
- Version: v4.0.2
```

**Comment by fb929** [comment]
can't reproduce
```
cat .env.override
EXTERNAL_LISTEN_HOSTS="127.0.0.2"
```
<img width="1433" alt="Screenshot 2024-05-04 at 15 48 20" src="https://github.com/anyproto/any-sync-dockercompose/assets/1324020/98291eb0-54e5-4f11-a8d7-8aaff3359aa7">

cat you show me your configuration client file? path "./etc/client.yml"

**Comment by ms-xie** [comment]
The port `100.100.182.62` is tailscale assign (another container in this Docker-in-Docker-DinD)

Also notice that I do not quote the ip, like this:
`EXTERNAL_LISTEN_HOSTS=100.100.182.62`

Could the problem be here?

`etc/client.yml`
```
id: 6631310efe1cab0019a5343e
networkId: N4GKRjMCc9Gs7AodExgyZE4SfhVAZyWrcZtVqw5eL3FKdpkd
nodes:
  - addresses:
      - any-sync-node-1:1001
      - quic://any-sync-node-1:1011
      - 100.100.182.62:1001
      - quic://100.100.182.62:1011
    peerId: 12D3KooWDJaL77GcLtskmE3L4spiqbk4SjPqzK91s32UuBqekNDw
    types:
      - tree
  - addresses:
      - any-sync-node-2:1002
      - quic://any-sync-node-2:1012
      - 100.100.182.62:1002
      - quic://100.100.182.62:1012
    peerId: 12D3KooWDgKEe3SJt5EzhhCcY4VWSnE81LuzVRNnhPdPvqknRUcZ
    types:
      - tree
  - addresses:
      - any-sync-node-3:1003
      - quic://any-sync-node-3:1013
      - 100.100.182.62:1003
      - quic://100.100.182.62:1013
    peerId: 12D3KooWMHqUAdqMeRiKrjNvyE2dVvzzYUsn4SYXzcjnruN8QVrz
    types:
      - tree
  - addresses:
      - any-sync-coordinator:1004
      - quic://any-sync-coordinator:1014
      - 100.100.182.62:1004
      - quic://100.100.182.62:1014
    peerId: 12D3KooWHofxyQLSR3KMbR7oZGigyrCxHvyRHiRCBC3cuTumDRTQ
    types:
      - coordinator
  - addresses:
      - any-sync-filenode:1005
      - quic://any-sync-filenode:1015
      - 100.100.182.62:1005
      - quic://100.100.182.62:1015
    peerId: 12D3KooWRo4eBuzwqhYE59GvSsjt61HYVFHrNiuGTW6vuTPzq48G
    types:
      - file
  - addresses:
      - any-sync-consensusnode:1006
      - quic://any-sync-consensusnode:1016
      - 100.100.182.62:1006
      - quic://100.100.182.62:1016
    peerId: 12D3KooWCXq9NPu6wTHegg5oW7VXqtpqk63w5q3obyqgrotyZXEz
    types:
      - consensus
```
