### ISSUE TITLE
Custom storage location

### ISSUE THREAD

**Issue by Onefabis** [anyproto/any-sync-dockercompose#69]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

If I setup server with SBC which has Linux on small ssd 128Gb I'd like to setup easily custom location for mounted HDD with 1TB of storage.

### Suggested solution

Please, add environment variable that allow to store Volume on bigger HDD drive

**Comment by fb929** [comment]
I added "STORAGE_DIR" variable https://github.com/anyproto/any-sync-dockercompose/releases/tag/v5.0.0
before use, please read the [update](https://github.com/anyproto/any-sync-dockercompose/wiki/Upgrade-Guide#upgrading-from-v4xx-to-v5xx) and [configuration](https://github.com/anyproto/any-sync-dockercompose/wiki/Configuration#custom-storage-directory) guides.

**Comment by Onefabis** [comment]
@fb929 after the update to 5.x.x version I got redis container unhealthy error, it disappeared somehow, but now mongo 'unhealthy' error appeared. Don't know why. Tried clean re-install without any luck.

**Comment by fb929** [comment]
@Onefabis did you moving files ?
https://github.com/anyproto/any-sync-dockercompose/wiki/Configuration#existing-setup

**Comment by Onefabis** [comment]
Sorry, that was my fault, forgot to add that lines to docker-compose.override.yml

```
services:
  mongo-1:
    healthcheck:
      test: echo "rs.initiate({_id:'${MONGO_REPLICA_SET}',members:[{_id:0,host:\"mongo-1:${MONGO_1_PORT}\"}]}).ok || rs.status().ok" | mongo —port ${MONGO_1_PORT} —quiet

```
