### ISSUE TITLE
Cannot connect to the selfhosted instace via full openvpn redirect

### ISSUE THREAD

**Issue by bytersproblem** [anyproto/any-sync-dockercompose#96]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I am trying to connect to my selfhosted anytype server via OpenVPN from work. I got the config file for the clients like this (some data removed). The OpenVPN config uses `redirecy gateway` which means that I am getting the home network address when I check my exteranal IP. I am connecting to OpenVPN via UDP 1194. All resources on the home network are reachable. 
```
id: 
networkId:
nodes:
  - addresses:
      - any-sync-node-1:1001
      - quic://any-sync-node-1:1011
      - 192.168.100.199:1001
      - quic://192.168.100.199:1011
    peerId: 
      - tree
  - addresses:
      - any-sync-node-2:1002
      - quic://any-sync-node-2:1012
      - 192.168.100.199:1002
      - quic://192.168.100.199:1012
    peerId: 
    types:
      - tree
  - addresses:
      - any-sync-node-3:1003
      - quic://any-sync-node-3:1013
      - 192.168.100.199:1003
      - quic://192.168.100.199:1013
    peerId: 
    types:
      - tree
  - addresses:
      - any-sync-coordinator:1004
      - quic://any-sync-coordinator:1014
      - 192.168.100.199:1004
      - quic://192.168.100.199:1014
    peerId: 
    types:
      - coordinator
  - addresses:
      - any-sync-filenode:1005
      - quic://any-sync-filenode:1015
      - 192.168.100.199:1005
      - quic://192.168.100.199:1015
    peerId: 
    types:
      - file
  - addresses:
      - any-sync-consensusnode:1006
      - quic://any-sync-consensusnode:1016
      - 192.168.100.199:1006
      - quic://192.168.100.199:1016
    peerId: 
    types:
      - consensus
  ```
Here is output of `sudo docker ps`

```
CONTAINER ID   IMAGE                                            COMMAND                  CREATED       STATUS                 PORTS                                                                                                                                                                                 NAMES
564bd38c50f8   ghcr.io/anyproto/any-sync-node:v0.3.34           "/bin/sh -c '/bin/an…"   6 weeks ago   Up 4 weeks             443/tcp, 0.0.0.0:1003->1003/tcp, :::1003->1003/tcp, 0.0.0.0:1013->1013/udp, :::1013->1013/udp, 0.0.0.0:8003->8000/tcp, :::8003->8000/tcp, 0.0.0.0:8083->8080/tcp, :::8083->8080/tcp   any-sync-dockercompose-any-sync-node-3-1
6f35d795b085   ghcr.io/anyproto/any-sync-filenode:v0.6.5        "/bin/sh -c '/bin/an…"   6 weeks ago   Up 4 weeks             443/tcp, 8080/tcp, 0.0.0.0:1005->1005/tcp, :::1005->1005/tcp, 0.0.0.0:1015->1015/udp, :::1015->1015/udp, 0.0.0.0:8004->8000/tcp, :::8004->8000/tcp                                    any-sync-dockercompose-any-sync-filenode-1
e237e1962596   ghcr.io/anyproto/any-sync-node:v0.3.34           "/bin/sh -c '/bin/an…"   6 weeks ago   Up 4 weeks             443/tcp, 0.0.0.0:1001->1001/tcp, :::1001->1001/tcp, 0.0.0.0:1011->1011/udp, :::1011->1011/udp, 0.0.0.0:8001->8000/tcp, :::8001->8000/tcp, 0.0.0.0:8081->8080/tcp, :::8081->8080/tcp   any-sync-dockercompose-any-sync-node-1-1
1cf48b275ad3   ghcr.io/anyproto/any-sync-node:v0.3.34           "/bin/sh -c '/bin/an…"   6 weeks ago   Up 4 weeks             443/tcp, 0.0.0.0:1002->1002/tcp, :::1002->1002/tcp, 0.0.0.0:1012->1012/udp, :::1012->1012/udp, 0.0.0.0:8002->8000/tcp, :::8002->8000/tcp, 0.0.0.0:8082->8080/tcp, :::8082->8080/tcp   any-sync-dockercompose-any-sync-node-2-1
090e5da52b01   ghcr.io/anyproto/any-sync-consensusnode:v0.1.7   "/bin/sh -c '/bin/an…"   6 weeks ago   Up 14 seconds          443/tcp, 8080/tcp, 0.0.0.0:1006->1006/tcp, :::1006->1006/tcp, 0.0.0.0:1016->1016/udp, :::1016->1016/udp, 0.0.0.0:8006->8000/tcp, :::8006->8000/tcp                                    any-sync-dockercompose-any-sync-consensusnode-1
3ac26928affc   ghcr.io/anyproto/any-sync-coordinator:v0.3.25    "/bin/sh -c '/bin/an…"   6 weeks ago   Up 4 weeks             443/tcp, 8080/tcp, 0.0.0.0:1004->1004/tcp, :::1004->1004/tcp, 0.0.0.0:1014->1014/udp, :::1014->1014/udp, 0.0.0.0:8005->8000/tcp, :::8005->8000/tcp                                    any-sync-dockercompose-any-sync-coordinator-1
ead4cfdf14a9   redis/redis-stack-server:7.2.0-v6                "redis-server --port…"   6 weeks ago   Up 4 weeks (healthy)   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp                                                                                                                                             any-sync-dockercompose-redis-1
3fa9864b8fc4   minio/minio:RELEASE.2024-07-04T14-25-45Z         "/usr/bin/docker-ent…"   6 weeks ago   Up 4 weeks (healthy)   0.0.0.0:9000-9001->9000-9001/tcp, :::9000-9001->9000-9001/tcp                                                                                                                         any-sync-dockercompose-minio-1
```

### Expected Behavior

To connect to my selfhosted vault

### Steps To Reproduce

Install containers as descibed on https://github.com/anyproto/any-sync-dockercompose
Forward ports mentioned
Upload conf file created on initial docker raise
Enter secret phrase
Error:
```
10:39:10.754 › {"level":"ERROR","ts":"2024-09-04T10:39:10.754+0200","logger":"service-metrics","msg":"failed to send messages","unsent messages":93}

{"level":"ERROR","ts":"2024-09-04T10:39:10.754+0200","logger":"service-metrics","msg":"failed to send messages","unsent messages":93}

```

### Environment

```markdown
- OS: Ubuntu 22.04 Server
- Version:
```
